language: node_js

node_js:
  - 10
  - 11
  - 12
  - 13

env:
  - INSTALL=yarn
  - INSTALL=npm


matrix:
  fast_finish: true

install:
  - if [ "yarn" == $INSTALL ]; then yarn install; fi
  - if [ "npm" == $INSTALL ]; then npm install; fi

script:
  - echo 'Tests must be configured'
