# Generated by Django 3.0.6 on 2020-05-15 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=13, verbose_name='教室id')),
                ('rloc', models.CharField(max_length=50, verbose_name='教室位置')),
            ],
            options={
                'verbose_name': '教室信息',
                'verbose_name_plural': '教室信息',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=13, unique=True, verbose_name='课程id')),
                ('cname', models.CharField(blank=True, max_length=50, verbose_name='课程名称')),
                ('credit', models.IntegerField(default=0, verbose_name='学分')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CouSignInfo',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('timeend', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Course')),
            ],
            options={
                'verbose_name': '课程签到',
                'verbose_name_plural': '课程签到',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=13, unique=True, verbose_name='学生id')),
                ('sname', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('secret', '保密'), ('male', '男'), ('female', '女')], default='secret', max_length=6, verbose_name='性别')),
                ('spasswd', models.CharField(default='123456', max_length=50, verbose_name='登陆密码')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=13, unique=True, verbose_name='教师id')),
                ('tname', models.CharField(blank=True, max_length=50, verbose_name='教师姓名')),
                ('tpasswd', models.CharField(default='123456', max_length=50, verbose_name='登录密码')),
                ('tauth', models.CharField(choices=[('normal', '普通教师'), ('admin', '管理员')], default='normal', max_length=7, verbose_name='教师权限')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.CreateModel(
            name='StuToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Course')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Student')),
            ],
            options={
                'verbose_name': '选课信息',
                'verbose_name_plural': '选课信息',
            },
        ),
        migrations.CreateModel(
            name='SignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='签到时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.CouSignInfo')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Student')),
            ],
            options={
                'verbose_name': '学生签到信息',
                'verbose_name_plural': '学生签到信息',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Teacher'),
        ),
        migrations.CreateModel(
            name='CouOnClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cday', models.CharField(choices=[('3', '周三'), ('1', '周一'), ('2', '周二'), ('4', '周四'), ('7', '周日'), ('6', '周六'), ('5', '周五')], default='Mon', max_length=5, verbose_name='上课星期')),
                ('ctime', models.TimeField(default=django.utils.timezone.now, verbose_name='上课时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Course')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Classroom')),
            ],
            options={
                'verbose_name': '上课信息',
                'verbose_name_plural': '上课信息',
            },
        ),
    ]
