# Generated by Django 3.0.5 on 2020-05-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=13, unique=True, verbose_name='学生id')),
                ('sname', models.CharField(blank=True, max_length=50, verbose_name='学生姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('female', '女'), ('male', '男'), ('secret', '保密')], default='secret', max_length=6, verbose_name='性别')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
