# Generated by Django 3.0 on 2020-05-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rloc', models.CharField(max_length=50, verbose_name='教室位置')),
                ('rid', models.CharField(max_length=50, verbose_name='教室id')),
            ],
            options={
                'verbose_name': '上课信息',
                'verbose_name_plural': '上课信息',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=13, unique=True, verbose_name='课程id')),
                ('cname', models.CharField(blank=True, max_length=50, verbose_name='课程名称')),
                ('credit', models.IntegerField(default=0, verbose_name='学分')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=13, unique=True, verbose_name='学生id')),
                ('sname', models.CharField(blank=True, max_length=50, verbose_name='学生姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('secret', '保密'), ('female', '女')], default='secret', max_length=6, verbose_name='性别')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=13, unique=True, verbose_name='教师id')),
                ('tname', models.CharField(blank=True, max_length=50, verbose_name='教师姓名')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.CreateModel(
            name='StuToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Course')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Student')),
            ],
            options={
                'verbose_name': '选课信息',
                'verbose_name_plural': '选课信息',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Teacher'),
        ),
        migrations.CreateModel(
            name='CouOnClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.CharField(max_length=30, verbose_name='上课时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Course')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Classroom')),
            ],
            options={
                'verbose_name': '上课信息',
                'verbose_name_plural': '上课信息',
            },
        ),
    ]
