# Generated by Django 3.0.5 on 2020-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('secret', '保密'), ('female', '女'), ('male', '男')], default='secret', max_length=6, verbose_name='性别'),
        ),
    ]
