# Generated by Django 3.0 on 2020-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_auto_20200505_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spasswd',
            field=models.CharField(default=123456, max_length=50, verbose_name='登陆密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='tpasswd',
            field=models.CharField(default=123456, max_length=50, verbose_name='登录密码'),
            preserve_default=False,
        ),
    ]
