# Generated by Django 3.0 on 2020-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_auto_20200505_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('secret', '保密'), ('female', '女')], default='secret', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spasswd',
            field=models.CharField(default='123456', max_length=50, verbose_name='登陆密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tpasswd',
            field=models.CharField(default='123456', max_length=50, verbose_name='登录密码'),
        ),
    ]
