# Generated by Django 3.0.5 on 2020-05-06 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_auto_20200505_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '教室信息', 'verbose_name_plural': '教室信息'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='rid',
            field=models.CharField(max_length=13, verbose_name='教室id'),
        ),
        migrations.AlterField(
            model_name='couonclass',
            name='ctime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('secret', '保密'), ('female', '女')], default='secret', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=50, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spasswd',
            field=models.CharField(default='123456', max_length=50, verbose_name='登陆密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=models.CharField(max_length=50, verbose_name='教师姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tpasswd',
            field=models.CharField(default='123456', max_length=50, verbose_name='登陆密码'),
        ),
        migrations.CreateModel(
            name='SignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signtime', models.DateTimeField(null=True, verbose_name='签到时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.CouOnClass')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Student')),
            ],
            options={
                'verbose_name': '签到信息',
                'verbose_name_plural': '签到信息',
            },
        ),
    ]
