# Generated by Django 3.0 on 2020-05-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0004_auto_20200505_2201'),
        ('background', '0005_auto_20200506_1625'),
    ]

    operations = [
    ]
