# Generated by Django 3.0.5 on 2020-05-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0005_auto_20200506_1625'),
        ('background', '0004_auto_20200505_2201'),
    ]

    operations = [
    ]
