# Generated by Django 3.0.5 on 2020-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0006_merge_20200506_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tauth',
            field=models.CharField(choices=[('normal', '普通教师'), ('admin', '管理员')], default='normal', max_length=7, verbose_name='教师权限'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('secret', '保密'), ('female', '女'), ('male', '男')], default='secret', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=models.CharField(blank=True, max_length=50, verbose_name='教师姓名'),
        ),
    ]
