# Generated by Django 3.0.5 on 2020-05-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0007_auto_20200506_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='couonclass',
            name='cday',
            field=models.CharField(choices=[('Thur', '周四'), ('Sun', '周日'), ('Tue', '周二'), ('Sat', '周六'), ('Mon', '周一'), ('Fri', '周五'), ('Wed', '周三')], default='Mon', max_length=5, verbose_name='上课星期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('secret', '保密'), ('male', '男'), ('female', '女')], default='secret', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tauth',
            field=models.CharField(choices=[('admin', '管理员'), ('normal', '普通教师')], default='normal', max_length=7, verbose_name='教师权限'),
        ),
    ]
