# Generated by Django 3.0 on 2020-05-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0006_merge_20200506_2100'),
        ('background', '0008_auto_20200506_1829'),
    ]

    operations = [
    ]
