# Generated by Django 3.0.5 on 2020-05-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0009_merge_20200508_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signinfo',
            options={'verbose_name': '学生签到信息', 'verbose_name_plural': '学生签到信息'},
        ),
        migrations.AlterField(
            model_name='couonclass',
            name='cday',
            field=models.CharField(choices=[('5', '周五'), ('4', '周四'), ('6', '周六'), ('1', '周一'), ('3', '周三'), ('0', '周日'), ('2', '周二')], default='Mon', max_length=5, verbose_name='上课星期'),
        ),
        migrations.AlterField(
            model_name='signinfo',
            name='signtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='签到时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男'), ('secret', '保密')], default='secret', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tauth',
            field=models.CharField(choices=[('normal', '普通教师'), ('admin', '管理员')], default='normal', max_length=7, verbose_name='教师权限'),
        ),
        migrations.CreateModel(
            name='CouSignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signtime', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.CouOnClass')),
            ],
            options={
                'verbose_name': '课程签到',
                'verbose_name_plural': '课程签到',
            },
        ),
        migrations.AlterField(
            model_name='signinfo',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.CouSignInfo'),
        ),
    ]
