# Generated by Django 3.0.5 on 2020-05-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0010_auto_20200509_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couonclass',
            name='cday',
            field=models.CharField(choices=[('2', '周二'), ('6', '周六'), ('1', '周一'), ('3', '周三'), ('5', '周五'), ('4', '周四'), ('0', '周日')], default='Mon', max_length=5, verbose_name='上课星期'),
        ),
        migrations.AlterField(
            model_name='cousigninfo',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.Course'),
        ),
    ]
