# Generated by Django 3.0.5 on 2020-05-09 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0011_auto_20200509_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cousigninfo',
            name='signtime',
        ),
        migrations.AddField(
            model_name='cousigninfo',
            name='timeend',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='cousigninfo',
            name='timestart',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='couonclass',
            name='cday',
            field=models.CharField(choices=[('1', '周一'), ('6', '周六'), ('2', '周二'), ('3', '周三'), ('0', '周日'), ('4', '周四'), ('5', '周五')], default='Mon', max_length=5, verbose_name='上课星期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tauth',
            field=models.CharField(choices=[('admin', '管理员'), ('normal', '普通教师')], default='normal', max_length=7, verbose_name='教师权限'),
        ),
    ]
