# Generated by Django 3.0.6 on 2020-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0014_auto_20200510_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couonclass',
            name='cday',
            field=models.CharField(choices=[('2', '周二'), ('3', '周三'), ('6', '周六'), ('1', '周一'), ('0', '周日'), ('4', '周四'), ('5', '周五')], default='Mon', max_length=5, verbose_name='上课星期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('secret', '保密'), ('male', '男')], default='secret', max_length=6, verbose_name='性别'),
        ),
    ]
