# Generated by Django 3.0 on 2020-05-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0017_auto_20200512_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couonclass',
            name='cday',
            field=models.CharField(choices=[('2', '周二'), ('5', '周五'), ('1', '周一'), ('0', '周日'), ('6', '周六'), ('3', '周三'), ('4', '周四')], default='Mon', max_length=5, verbose_name='上课星期'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=13, unique=True, verbose_name='课程id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('secret', '保密'), ('female', '女')], default='secret', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=13, unique=True, verbose_name='学生id'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.CharField(max_length=13, unique=True, verbose_name='教师id'),
        ),
    ]
