# Generated by Django 3.0.6 on 2020-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0018_auto_20200512_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couonclass',
            name='cday',
            field=models.CharField(choices=[('4', '周四'), ('2', '周二'), ('7', '周日'), ('3', '周三'), ('1', '周一'), ('6', '周六'), ('5', '周五')], default='Mon', max_length=5, verbose_name='上课星期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('secret', '保密'), ('male', '男')], default='secret', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tauth',
            field=models.CharField(choices=[('admin', '管理员'), ('normal', '普通教师')], default='normal', max_length=7, verbose_name='教师权限'),
        ),
    ]
